# Generated by Django 6.0.1 on 2026-02-05 11:46

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CreateExtension('vector'),
    ]

