# Generated by Django 6.0.1 on 2026-02-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_at_purchase',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_snapshot',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant_snapshot',
            field=models.JSONField(),
        ),
    ]
